function viewpnt(action)
% VIEWPNT - puts buttons on a plot to adjust the viewpoint 
%


% Author D. A. Byrne?

if nargin<1,
	action='initialize';
end;
fig=gcf;
if strcmp(action,'initialize'),
	sli_azm=uicontrol(fig,...
		'style','slider',...
		'position',[50,25,120,20],...
		'min',-90,'max',90,'value',30,...
		'callback','viewpnt(''changeview'')'...
		);
	sli_elv=uicontrol(fig,...
        	'style','slider',...
        	'position',[240 25 120 20],...
        	'min',-90,'max',90,'value',30,...
        	'callback','viewpnt(''changeview'')'...
		);
	azm_min = uicontrol(fig,...
		'style','text',...
		'pos',[20 25 30 20],...
		'string',num2str(get(sli_azm,'min')));
	elv_min = uicontrol(fig,...
		'style','text',...
		'pos',[210 25 30 20],...
		'string',num2str(get(sli_elv,'min')));
	azm_max = uicontrol(fig,...
		'style','text',...
		'pos',[170 25 30 20],...
		'string',num2str(get(sli_azm,'max')),...
		'horiz','right');
	elv_max = uicontrol(fig,...
		'style','text',...
		'pos',[360 25 30 20],...
		'string',num2str(get(sli_elv,'max')),...
		'horiz','right');
	azm_cur = uicontrol(fig,...
		'style','text',...
		'pos',[090 5 50 20],...
		'string',num2str(get(sli_azm,'value')));
	elv_cur = uicontrol(fig,...
		'style','text',...
		'pos',[280  5 50 20],...
		'string',num2str(get(sli_elv,'value')));
	set(gcf,'UserData',[sli_azm,sli_elv,azm_cur,elv_cur]);
elseif strcmp(action,'changeview'),
	uihandles=get(gcf,'UserData');
	sli_azm=uihandles(1);
	sli_elv=uihandles(2);
	azm_cur=uihandles(3);
	elv_cur=uihandles(4);

	set(azm_cur,'string',num2str(get(sli_azm,'val')));
	set(gca,'view',[get(sli_azm,'val'),get(sli_elv,'val')]);
        set(elv_cur,'string',num2str(get(sli_elv,'val')));
        set(gca,'view',[get(sli_azm,'val'),get(sli_elv,'val')]);

end;
return;

